version: 2.1

commands:
  install_retry:
    description: "Install moul.io/retry"
    parameters:
      version:
        type: string
        default: "v0.5.0"
    steps:
      - run:
          name: installing moul.io/retry
          command: |
            command -v wget &>/dev/null && wget -O /tmp/retry "https://github.com/moul/retry/releases/download/<< parameters.version >>/retry_$(uname -s)_$(uname -m)" || true
            if [ ! -f /tmp/retry ]; then command -v curl &>/dev/null && curl -L -o /tmp/retry "https://github.com/moul/retry/releases/download/<< parameters.version >>/retry_$(uname -s)_$(uname -m)"; fi
            chmod +x /tmp/retry
            /tmp/retry --version

"-": &dockerbuild
  steps:
    - install_retry:
        version: "v0.5.0"

jobs:
  test-circleci-node:
    docker:
      - image: circleci/node
    <<: *dockerbuild
  test-circleci-golang:
    docker:
      - image: circleci/golang
    <<: *dockerbuild
  test-circleci-python:
    docker:
      - image: circleci/python
    <<: *dockerbuild
  test-alpine:
    docker:
      - image: alpine
    <<: *dockerbuild

workflows:
  version: 2
  test-all:
    jobs:
      - test-circleci-node
      - test-circleci-golang
      - test-circleci-python
      - test-alpine
