version: 2.1

commands:
  install_golangci-lint:
    description: "Install golangci-lint"
    parameters:
      version:
        type: string
        default: "v1.15.0"
      sudo:
        type: boolean
        default: false
      insecure:
        type: boolean
        default: false
    steps:
      - retry/install:
          sudo: << parameters.sudo >>
          insecure: << parameters.insecure >>
      - run:
          name: "Installing golangci-lint"
          command: |
            . ~/.profile
            command -v golangci-lint ^>/dev/null || (
              cd
              dl --insecure="<< parameters.insecure >>" -o - https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | retry -m 3 sh -s << parameters.version >>
              echo "export PATH=~/bin:$PATH" >> $BASH_ENV
            )
            PATH=${HOME}/bin golangci-lint --version

  install_curl:
    description: "Install curl (if missing)"
    steps:
      - run:
          name: installing curl
          command: |
            command -v curl &>/dev/null || (
              apk add --no-cache curl || (apt update && apt install curl)
            )
            curl --version

  test:
    description: "Internal: testing the orb."
    parameters:
      sudo:
        type: boolean
        default: false
      insecure:
        type: boolean
        default: false
    steps:
      - install_golangci-lint:
          sudo: << parameters.sudo >>
          insecure: << parameters.insecure >>
      - run: retry --version
      - run: . ~/.profile && golangci-lint --version

orbs:
  dl: moul/dl@1.7.0
  retry: moul/retry@0.6.0

jobs:
  test-circleci-node:
    docker:
      - image: circleci/node
    steps:
      - test
  test-circleci-golang:
    docker:
      - image: circleci/golang
    steps:
      - test
  test-circleci-python:
    docker:
      - image: circleci/python
    steps:
      - test
  test-alpine:
    docker:
      - image: alpine
    steps:
      - test:
          insecure: true

workflows:
  main:
    jobs:
      - test-circleci-node
      - test-circleci-golang
      - test-circleci-python
      - test-alpine
